/*
 * $Copyright Open Broadcom Corporation$
 */

#include <linux/interrupt.h>
#include <linux/irqchip/arm-gic.h>
#include <linux/irq.h>
#include <asm/io.h>
#include <linux/of.h>
#include <linux/of_irq.h>
#include <linux/of_address.h>
#include <linux/of_device.h>

extern void __iomem *get_iproc_idm_base(int);
extern void __iomem *get_iproc_idm_base_phys(int);

#if defined(CONFIG_MACH_HX4) || defined(CONFIG_MACH_KT2) || \
		defined(CONFIG_MACH_HR2)
#define IHOST_S1_IDM_ERROR_LOG_CONTROL 0x18107900
#define IHOST_S1_IDM_ERROR_LOG_COMPLETE 0x18107904
#define IHOST_S1_IDM_ERROR_LOG_STATUS 0x18107908
#define IHOST_S1_IDM_ERROR_LOG_ADDR_LSB 0x1810790c
#define IHOST_S1_IDM_ERROR_LOG_ID 0x18107914
#define IHOST_S1_IDM_ERROR_LOG_FLAGS 0x1810791c
#define IHOST_S1_IDM_INTERRUPT_STATUS 0x18107a00
#define IHOST_S0_IDM_ERROR_LOG_CONTROL 0x18108900
#define IHOST_S0_IDM_ERROR_LOG_COMPLETE 0x18108904
#define IHOST_S0_IDM_ERROR_LOG_STATUS 0x18108908
#define IHOST_S0_IDM_ERROR_LOG_ADDR_LSB 0x1810890c
#define IHOST_S0_IDM_ERROR_LOG_ID 0x18108914
#define IHOST_S0_IDM_ERROR_LOG_FLAGS 0x1810891c
#define IHOST_S0_IDM_INTERRUPT_STATUS 0x18108a00
#define DDR_S1_IDM_ERROR_LOG_CONTROL 0x18109900
#define DDR_S1_IDM_ERROR_LOG_COMPLETE 0x18109904
#define DDR_S1_IDM_ERROR_LOG_STATUS 0x18109908
#define DDR_S1_IDM_ERROR_LOG_ADDR_LSB 0x1810990c
#define DDR_S1_IDM_ERROR_LOG_ID 0x18109914
#define DDR_S1_IDM_ERROR_LOG_FLAGS 0x1810991c
#define DDR_S1_IDM_INTERRUPT_STATUS 0x18109a00
#define DDR_S2_IDM_ERROR_LOG_CONTROL 0x1810a900
#define DDR_S2_IDM_ERROR_LOG_COMPLETE 0x1810a904
#define DDR_S2_IDM_ERROR_LOG_STATUS 0x1810a908
#define DDR_S2_IDM_ERROR_LOG_ADDR_LSB 0x1810a90c
#define DDR_S2_IDM_ERROR_LOG_ID 0x1810a914
#define DDR_S2_IDM_ERROR_LOG_FLAGS 0x1810a91c
#define DDR_S2_IDM_INTERRUPT_STATUS 0x1810aa00
#define AXI_PCIE_S0_IDM_IDM_ERROR_LOG_CONTROL 0x1810b900
#define AXI_PCIE_S0_IDM_IDM_ERROR_LOG_COMPLETE 0x1810b904
#define AXI_PCIE_S0_IDM_IDM_ERROR_LOG_STATUS 0x1810b908
#define AXI_PCIE_S0_IDM_IDM_ERROR_LOG_ADDR_LSB 0x1810b90c
#define AXI_PCIE_S0_IDM_IDM_ERROR_LOG_ID 0x1810b914
#define AXI_PCIE_S0_IDM_IDM_ERROR_LOG_FLAGS 0x1810b91c
#define AXI_PCIE_S0_IDM_IDM_INTERRUPT_STATUS 0x1810ba00
#define CMICD_S0_IDM_IDM_ERROR_LOG_CONTROL 0x1810d900
#define CMICD_S0_IDM_IDM_ERROR_LOG_COMPLETE 0x1810d904
#define CMICD_S0_IDM_IDM_ERROR_LOG_STATUS 0x1810d908
#define CMICD_S0_IDM_IDM_ERROR_LOG_ADDR_LSB 0x1810d90c
#define CMICD_S0_IDM_IDM_ERROR_LOG_ID 0x1810d914
#define CMICD_S0_IDM_IDM_ERROR_LOG_FLAGS 0x1810d91c
#define CMICD_S0_IDM_IDM_INTERRUPT_STATUS 0x1810da00
#define APBY_S0_IDM_IDM_ERROR_LOG_CONTROL 0x1810f900
#define APBY_S0_IDM_IDM_ERROR_LOG_COMPLETE 0x1810f904
#define APBY_S0_IDM_IDM_ERROR_LOG_STATUS 0x1810f908
#define APBY_S0_IDM_IDM_ERROR_LOG_ADDR_LSB 0x1810f90c
#define APBY_S0_IDM_IDM_ERROR_LOG_ID 0x1810f914
#define APBY_S0_IDM_IDM_ERROR_LOG_FLAGS 0x1810f91c
#define APBY_S0_IDM_IDM_INTERRUPT_STATUS 0x1810fa00
#define ROM_S0_IDM_ERROR_LOG_CONTROL 0x1811a900
#define ROM_S0_IDM_ERROR_LOG_COMPLETE 0x1811a904
#define ROM_S0_IDM_ERROR_LOG_STATUS 0x1811a908
#define ROM_S0_IDM_ERROR_LOG_ADDR_LSB 0x1811a90c
#define ROM_S0_IDM_ERROR_LOG_ID 0x1811a914
#define ROM_S0_IDM_ERROR_LOG_FLAGS 0x1811a91c
#define ROM_S0_IDM_INTERRUPT_STATUS 0x1811aa00
#define NAND_IDM_IDM_ERROR_LOG_CONTROL 0x1811b900
#define NAND_IDM_IDM_ERROR_LOG_COMPLETE 0x1811b904
#define NAND_IDM_IDM_ERROR_LOG_STATUS 0x1811b908
#define NAND_IDM_IDM_ERROR_LOG_ADDR_LSB 0x1811b90c
#define NAND_IDM_IDM_ERROR_LOG_ID 0x1811b914
#define NAND_IDM_IDM_ERROR_LOG_FLAGS 0x1811b91c
#define NAND_IDM_IDM_INTERRUPT_STATUS 0x1811ba00
#define QSPI_IDM_IDM_ERROR_LOG_CONTROL 0x1811c900
#define QSPI_IDM_IDM_ERROR_LOG_COMPLETE 0x1811c904
#define QSPI_IDM_IDM_ERROR_LOG_STATUS 0x1811c908
#define QSPI_IDM_IDM_ERROR_LOG_ADDR_LSB 0x1811c90c
#define QSPI_IDM_IDM_ERROR_LOG_ID 0x1811c914
#define QSPI_IDM_IDM_ERROR_LOG_FLAGS 0x1811c91c
#define QSPI_IDM_IDM_INTERRUPT_STATUS 0x1811ca00
#define A9JTAG_S0_IDM_IDM_ERROR_LOG_CONTROL 0x1811d900
#define A9JTAG_S0_IDM_IDM_ERROR_LOG_COMPLETE 0x1811d904
#define A9JTAG_S0_IDM_IDM_ERROR_LOG_STATUS 0x1811d908
#define A9JTAG_S0_IDM_IDM_ERROR_LOG_ADDR_LSB 0x1811d90c
#define A9JTAG_S0_IDM_IDM_ERROR_LOG_ID 0x1811d914
#define A9JTAG_S0_IDM_IDM_ERROR_LOG_FLAGS 0x1811d91c
#define A9JTAG_S0_IDM_IDM_INTERRUPT_STATUS 0x1811da00
#define SRAM_S0_IDM_ERROR_LOG_CONTROL 0x18120900
#define SRAM_S0_IDM_ERROR_LOG_COMPLETE 0x18120904
#define SRAM_S0_IDM_ERROR_LOG_STATUS 0x18120908
#define SRAM_S0_IDM_ERROR_LOG_ADDR_LSB 0x1812090c
#define SRAM_S0_IDM_ERROR_LOG_ID 0x18120914
#define SRAM_S0_IDM_ERROR_LOG_FLAGS 0x1812091c
#define SRAM_S0_IDM_INTERRUPT_STATUS 0x18120a00
#define APBZ_S0_IDM_IDM_ERROR_LOG_CONTROL 0x18121900
#define APBZ_S0_IDM_IDM_ERROR_LOG_COMPLETE 0x18121904
#define APBZ_S0_IDM_IDM_ERROR_LOG_STATUS 0x18121908
#define APBZ_S0_IDM_IDM_ERROR_LOG_ADDR_LSB 0x1812190c
#define APBZ_S0_IDM_IDM_ERROR_LOG_ID 0x18121914
#define APBZ_S0_IDM_IDM_ERROR_LOG_FLAGS 0x1812191c
#define APBZ_S0_IDM_IDM_INTERRUPT_STATUS 0x18121a00
#define AXIIC_DS_3_IDM_ERROR_LOG_CONTROL 0x18123900
#define AXIIC_DS_3_IDM_ERROR_LOG_COMPLETE 0x18123904
#define AXIIC_DS_3_IDM_ERROR_LOG_STATUS 0x18123908
#define AXIIC_DS_3_IDM_ERROR_LOG_ADDR_LSB 0x1812390c
#define AXIIC_DS_3_IDM_ERROR_LOG_ID 0x18123914
#define AXIIC_DS_3_IDM_ERROR_LOG_FLAGS 0x1812391c
#define AXIIC_DS_3_IDM_INTERRUPT_STATUS 0x18123a00
#define APBW_IDM_IDM_ERROR_LOG_CONTROL 0x18131900
#define APBW_IDM_IDM_ERROR_LOG_COMPLETE 0x18131904
#define APBW_IDM_IDM_ERROR_LOG_STATUS 0x18131908
#define APBW_IDM_IDM_ERROR_LOG_ADDR_LSB 0x1813190c
#define APBW_IDM_IDM_ERROR_LOG_ID 0x18131914
#define APBW_IDM_IDM_ERROR_LOG_FLAGS 0x1813191c
#define APBW_IDM_IDM_INTERRUPT_STATUS 0x18131a00
#define APBX_IDM_IDM_ERROR_LOG_CONTROL 0x18132900
#define APBX_IDM_IDM_ERROR_LOG_COMPLETE 0x18132904
#define APBX_IDM_IDM_ERROR_LOG_STATUS 0x18132908
#define APBX_IDM_IDM_ERROR_LOG_ADDR_LSB 0x1813290c
#define APBX_IDM_IDM_ERROR_LOG_ID 0x18132914
#define APBX_IDM_IDM_ERROR_LOG_FLAGS 0x1813291c
#define APBX_IDM_IDM_INTERRUPT_STATUS 0x18132a00
#define AXIIC_DS_0_IDM_ERROR_LOG_CONTROL 0x18141900
#define AXIIC_DS_0_IDM_ERROR_LOG_COMPLETE 0x18141904
#define AXIIC_DS_0_IDM_ERROR_LOG_STATUS 0x18141908
#define AXIIC_DS_0_IDM_ERROR_LOG_ADDR_LSB 0x1814190c
#define AXIIC_DS_0_IDM_ERROR_LOG_ID 0x18141914
#define AXIIC_DS_0_IDM_ERROR_LOG_FLAGS 0x1814191c
#define AXIIC_DS_0_IDM_INTERRUPT_STATUS 0x18141a00

#elif defined(CONFIG_MACH_HR3)

#define IHOST_S0_IDM_ERROR_LOG_CONTROL 0x18107900
#define IHOST_S0_IDM_ERROR_LOG_COMPLETE 0x18107904
#define IHOST_S0_IDM_ERROR_LOG_STATUS 0x18107908
#define IHOST_S0_IDM_ERROR_LOG_ADDR_LSB 0x1810790c
#define IHOST_S0_IDM_ERROR_LOG_ID 0x18107914
#define IHOST_S0_IDM_ERROR_LOG_FLAGS 0x1810791c
#define IHOST_S0_IDM_INTERRUPT_STATUS 0x18107a00
#define IHOST_S1_IDM_ERROR_LOG_CONTROL 0x18106900
#define IHOST_S1_IDM_ERROR_LOG_COMPLETE 0x18106904
#define IHOST_S1_IDM_ERROR_LOG_STATUS 0x18106908
#define IHOST_S1_IDM_ERROR_LOG_ADDR_LSB 0x1810690c
#define IHOST_S1_IDM_ERROR_LOG_ID 0x18106914
#define IHOST_S1_IDM_ERROR_LOG_FLAGS 0x1810691c
#define IHOST_S1_IDM_INTERRUPT_STATUS 0x18106a00
#define AXI_PCIE_S0_IDM_IDM_ERROR_LOG_CONTROL 0x18108900
#define AXI_PCIE_S0_IDM_IDM_ERROR_LOG_COMPLETE 0x18108904
#define AXI_PCIE_S0_IDM_IDM_ERROR_LOG_STATUS 0x18108908
#define AXI_PCIE_S0_IDM_IDM_ERROR_LOG_ADDR_LSB 0x1810890c
#define AXI_PCIE_S0_IDM_IDM_ERROR_LOG_ID 0x18108914
#define AXI_PCIE_S0_IDM_IDM_ERROR_LOG_FLAGS 0x1810891c
#define AXI_PCIE_S0_IDM_IDM_INTERRUPT_STATUS 0x18108a00
#define CMICD_S0_IDM_IDM_ERROR_LOG_CONTROL 0x1810a900
#define CMICD_S0_IDM_IDM_ERROR_LOG_COMPLETE 0x1810a904
#define CMICD_S0_IDM_IDM_ERROR_LOG_STATUS 0x1810a908
#define CMICD_S0_IDM_IDM_ERROR_LOG_ADDR_LSB 0x1810a90c
#define CMICD_S0_IDM_IDM_ERROR_LOG_ID 0x1810a914
#define CMICD_S0_IDM_IDM_ERROR_LOG_FLAGS 0x1810a91c
#define CMICD_S0_IDM_IDM_INTERRUPT_STATUS 0x1810aa00
#define A9JTAG_S0_IDM_IDM_ERROR_LOG_CONTROL 0x18119900
#define A9JTAG_S0_IDM_IDM_ERROR_LOG_COMPLETE 0x18119904
#define A9JTAG_S0_IDM_IDM_ERROR_LOG_STATUS 0x18119908
#define A9JTAG_S0_IDM_IDM_ERROR_LOG_ADDR_LSB 0x1811990c
#define A9JTAG_S0_IDM_IDM_ERROR_LOG_ID 0x18119914
#define A9JTAG_S0_IDM_IDM_ERROR_LOG_FLAGS 0x1811991c
#define A9JTAG_S0_IDM_IDM_INTERRUPT_STATUS 0x18119a00
#define APBX_IDM_IDM_ERROR_LOG_CONTROL 0x18130900
#define APBX_IDM_IDM_ERROR_LOG_COMPLETE 0x18130904
#define APBX_IDM_IDM_ERROR_LOG_STATUS 0x18130908
#define APBX_IDM_IDM_ERROR_LOG_ADDR_LSB 0x1813090c
#define APBX_IDM_IDM_ERROR_LOG_ID 0x18130914
#define APBX_IDM_IDM_ERROR_LOG_FLAGS 0x1813091c
#define APBX_IDM_IDM_INTERRUPT_STATUS 0x18130a00
#define DDR_S1_IDM_ERROR_LOG_CONTROL 0x18104900
#define DDR_S1_IDM_ERROR_LOG_COMPLETE 0x18104904
#define DDR_S1_IDM_ERROR_LOG_STATUS 0x18104908
#define DDR_S1_IDM_ERROR_LOG_ADDR_LSB 0x1810490c
#define DDR_S1_IDM_ERROR_LOG_ID 0x18104914
#define DDR_S1_IDM_ERROR_LOG_FLAGS 0x1810491c
#define DDR_S1_IDM_INTERRUPT_STATUS 0x18104a00
#define DDR_S2_IDM_ERROR_LOG_CONTROL 0x18105900
#define DDR_S2_IDM_ERROR_LOG_COMPLETE 0x18105904
#define DDR_S2_IDM_ERROR_LOG_STATUS 0x18105908
#define DDR_S2_IDM_ERROR_LOG_ADDR_LSB 0x1810590c
#define DDR_S2_IDM_ERROR_LOG_ID 0x18105914
#define DDR_S2_IDM_ERROR_LOG_FLAGS 0x1810591c
#define DDR_S2_IDM_INTERRUPT_STATUS 0x18105a00
#define ROM_S0_IDM_ERROR_LOG_CONTROL 0x1811a900
#define ROM_S0_IDM_ERROR_LOG_COMPLETE 0x1811a904
#define ROM_S0_IDM_ERROR_LOG_STATUS 0x1811a908
#define ROM_S0_IDM_ERROR_LOG_ADDR_LSB 0x1811a90c
#define ROM_S0_IDM_ERROR_LOG_ID 0x1811a914
#define ROM_S0_IDM_ERROR_LOG_FLAGS 0x1811a91c
#define ROM_S0_IDM_INTERRUPT_STATUS 0x1811aa00
#define NAND_IDM_IDM_ERROR_LOG_CONTROL 0x1811d900
#define NAND_IDM_IDM_ERROR_LOG_COMPLETE 0x1811d904
#define NAND_IDM_IDM_ERROR_LOG_STATUS 0x1811d908
#define NAND_IDM_IDM_ERROR_LOG_ADDR_LSB 0x1811d90c
#define NAND_IDM_IDM_ERROR_LOG_ID 0x1811d914
#define NAND_IDM_IDM_ERROR_LOG_FLAGS 0x1811d91c
#define NAND_IDM_IDM_INTERRUPT_STATUS 0x1811da00
#define QSPI_IDM_IDM_ERROR_LOG_CONTROL 0x1811f900
#define QSPI_IDM_IDM_ERROR_LOG_COMPLETE 0x1811f904
#define QSPI_IDM_IDM_ERROR_LOG_STATUS 0x1811f908
#define QSPI_IDM_IDM_ERROR_LOG_ADDR_LSB 0x1811f90c
#define QSPI_IDM_IDM_ERROR_LOG_ID 0x1811f914
#define QSPI_IDM_IDM_ERROR_LOG_FLAGS 0x1811f91c
#define QSPI_IDM_IDM_INTERRUPT_STATUS 0x1811fa00
#define AXIIC_DS_0_IDM_ERROR_LOG_CONTROL 0x18120900
#define AXIIC_DS_0_IDM_ERROR_LOG_COMPLETE 0x18120904
#define AXIIC_DS_0_IDM_ERROR_LOG_STATUS 0x18120908
#define AXIIC_DS_0_IDM_ERROR_LOG_ADDR_LSB 0x1812090c
#define AXIIC_DS_0_IDM_ERROR_LOG_ID 0x18120914
#define AXIIC_DS_0_IDM_ERROR_LOG_FLAGS 0x1812091c
#define AXIIC_DS_0_IDM_INTERRUPT_STATUS 0x18120a00

#elif defined(CONFIG_MACH_GH) || defined(CONFIG_MACH_SB2) || \
		defined(CONFIG_MACH_GH2)

#define IHOST_S0_IDM_ERROR_LOG_CONTROL			0x18107900
#define IHOST_S0_IDM_ERROR_LOG_COMPLETE			0x18107904
#define IHOST_S0_IDM_ERROR_LOG_STATUS			0x18107908
#define IHOST_S0_IDM_ERROR_LOG_ADDR_LSB			0x1810790c
#define IHOST_S0_IDM_ERROR_LOG_ID			0x18107914
#define IHOST_S0_IDM_ERROR_LOG_FLAGS			0x1810791c
#define IHOST_S0_IDM_INTERRUPT_STATUS			0x18107a00
#define IHOST_S1_IDM_ERROR_LOG_CONTROL			0x18106900
#define IHOST_S1_IDM_ERROR_LOG_COMPLETE			0x18106904
#define IHOST_S1_IDM_ERROR_LOG_STATUS			0x18106908
#define IHOST_S1_IDM_ERROR_LOG_ADDR_LSB			0x1810690c
#define IHOST_S1_IDM_ERROR_LOG_ID			0x18106914
#define IHOST_S1_IDM_ERROR_LOG_FLAGS			0x1810691c
#define IHOST_S1_IDM_INTERRUPT_STATUS			0x18106a00
#define AXI_PCIE_S0_IDM_IDM_ERROR_LOG_CONTROL		0x18108900
#define AXI_PCIE_S0_IDM_IDM_ERROR_LOG_COMPLETE		0x18108904
#define AXI_PCIE_S0_IDM_IDM_ERROR_LOG_STATUS		0x18108908
#define AXI_PCIE_S0_IDM_IDM_ERROR_LOG_ADDR_LSB		0x1810890c
#define AXI_PCIE_S0_IDM_IDM_ERROR_LOG_ID		0x18108914
#define AXI_PCIE_S0_IDM_IDM_ERROR_LOG_FLAGS		0x1810891c
#define AXI_PCIE_S0_IDM_IDM_INTERRUPT_STATUS		0x18108a00
#define CMICD_S0_IDM_IDM_ERROR_LOG_CONTROL		0x1810a900
#define CMICD_S0_IDM_IDM_ERROR_LOG_COMPLETE		0x1810a904
#define CMICD_S0_IDM_IDM_ERROR_LOG_STATUS		0x1810a908
#define CMICD_S0_IDM_IDM_ERROR_LOG_ADDR_LSB		0x1810a90c
#define CMICD_S0_IDM_IDM_ERROR_LOG_ID			0x1810a914
#define CMICD_S0_IDM_IDM_ERROR_LOG_FLAGS		0x1810a91c
#define CMICD_S0_IDM_IDM_INTERRUPT_STATUS		0x1810aa00
#define A9JTAG_S0_IDM_IDM_ERROR_LOG_CONTROL		0x18119900
#define A9JTAG_S0_IDM_IDM_ERROR_LOG_COMPLETE		0x18119904
#define A9JTAG_S0_IDM_IDM_ERROR_LOG_STATUS		0x18119908
#define A9JTAG_S0_IDM_IDM_ERROR_LOG_ADDR_LSB		0x1811990c
#define A9JTAG_S0_IDM_IDM_ERROR_LOG_ID			0x18119914
#define A9JTAG_S0_IDM_IDM_ERROR_LOG_FLAGS		0x1811991c
#define A9JTAG_S0_IDM_IDM_INTERRUPT_STATUS		0x18119a00
#define SRAM_S0_IDM_ERROR_LOG_CONTROL			0x1811b900
#define SRAM_S0_IDM_ERROR_LOG_COMPLETE			0x1811b904
#define SRAM_S0_IDM_ERROR_LOG_STATUS			0x1811b908
#define SRAM_S0_IDM_ERROR_LOG_ADDR_LSB			0x1811b90c
#define SRAM_S0_IDM_ERROR_LOG_ID			0x1811b914
#define SRAM_S0_IDM_ERROR_LOG_FLAGS			0x1811b91c
#define SRAM_S0_IDM_INTERRUPT_STATUS			0x1811ba00
#define APBX_IDM_IDM_ERROR_LOG_CONTROL			0x18130900
#define APBX_IDM_IDM_ERROR_LOG_COMPLETE			0x18130904
#define APBX_IDM_IDM_ERROR_LOG_STATUS			0x18130908
#define APBX_IDM_IDM_ERROR_LOG_ADDR_LSB			0x1813090c
#define APBX_IDM_IDM_ERROR_LOG_ID			0x18130914
#define APBX_IDM_IDM_ERROR_LOG_FLAGS			0x1813091c
#define APBX_IDM_IDM_INTERRUPT_STATUS			0x18130a00
#define DDR_S1_IDM_ERROR_LOG_CONTROL			0xf8102900
#define DDR_S1_IDM_ERROR_LOG_COMPLETE			0xf8102904
#define DDR_S1_IDM_ERROR_LOG_STATUS			0xf8102908
#define DDR_S1_IDM_ERROR_LOG_ADDR_LSB			0xf810290c
#define DDR_S1_IDM_ERROR_LOG_ID				0xf8102914
#define DDR_S1_IDM_ERROR_LOG_FLAGS			0xf810291c
#define DDR_S1_IDM_INTERRUPT_STATUS			0xf8102a00
#define DDR_S2_IDM_ERROR_LOG_CONTROL			0xf8103900
#define DDR_S2_IDM_ERROR_LOG_COMPLETE			0xf8103904
#define DDR_S2_IDM_ERROR_LOG_STATUS			0xf8103908
#define DDR_S2_IDM_ERROR_LOG_ADDR_LSB			0xf810390c
#define DDR_S2_IDM_ERROR_LOG_ID				0xf8103914
#define DDR_S2_IDM_ERROR_LOG_FLAGS			0xf810391c
#define DDR_S2_IDM_INTERRUPT_STATUS			0xf8103a00
#define ROM_S0_IDM_ERROR_LOG_CONTROL			0xf8104900
#define ROM_S0_IDM_ERROR_LOG_COMPLETE			0xf8104904
#define ROM_S0_IDM_ERROR_LOG_STATUS			0xf8104908
#define ROM_S0_IDM_ERROR_LOG_ADDR_LSB			0xf810490c
#define ROM_S0_IDM_ERROR_LOG_ID				0xf8104914
#define ROM_S0_IDM_ERROR_LOG_FLAGS			0xf810491c
#define ROM_S0_IDM_INTERRUPT_STATUS			0xf8104a00
#define NAND_IDM_IDM_ERROR_LOG_CONTROL			0xf8105900
#define NAND_IDM_IDM_ERROR_LOG_COMPLETE			0xf8105904
#define NAND_IDM_IDM_ERROR_LOG_STATUS			0xf8105908
#define NAND_IDM_IDM_ERROR_LOG_ADDR_LSB			0xf810590c
#define NAND_IDM_IDM_ERROR_LOG_ID			0xf8105914
#define NAND_IDM_IDM_ERROR_LOG_FLAGS			0xf810591c
#define NAND_IDM_IDM_INTERRUPT_STATUS			0xf8105a00
#define QSPI_IDM_IDM_ERROR_LOG_CONTROL			0xf8106900
#define QSPI_IDM_IDM_ERROR_LOG_COMPLETE			0xf8106904
#define QSPI_IDM_IDM_ERROR_LOG_STATUS			0xf8106908
#define QSPI_IDM_IDM_ERROR_LOG_ADDR_LSB			0xf810690c
#define QSPI_IDM_IDM_ERROR_LOG_ID			0xf8106914
#define QSPI_IDM_IDM_ERROR_LOG_FLAGS			0xf810691c
#define QSPI_IDM_IDM_INTERRUPT_STATUS			0xf8106a00
#define AXIIC_DS_0_IDM_ERROR_LOG_CONTROL		0x18120900
#define AXIIC_DS_0_IDM_ERROR_LOG_COMPLETE		0x18120904
#define AXIIC_DS_0_IDM_ERROR_LOG_STATUS			0x18120908
#define AXIIC_DS_0_IDM_ERROR_LOG_ADDR_LSB		0x1812090c
#define AXIIC_DS_0_IDM_ERROR_LOG_ID			0x18120914
#define AXIIC_DS_0_IDM_ERROR_LOG_FLAGS			0x1812091c
#define AXIIC_DS_0_IDM_INTERRUPT_STATUS			0x18120a00
#if !defined(CONFIG_MACH_GH2)
#define AXIIC_DS_3_IDM_ERROR_LOG_CONTROL		0x1811e900
#define AXIIC_DS_3_IDM_ERROR_LOG_COMPLETE		0x1811e904
#define AXIIC_DS_3_IDM_ERROR_LOG_STATUS			0x1811e908
#define AXIIC_DS_3_IDM_ERROR_LOG_ADDR_LSB		0x1811e90c
#define AXIIC_DS_3_IDM_ERROR_LOG_ID			0x1811e914
#define AXIIC_DS_3_IDM_ERROR_LOG_FLAGS			0x1811e91c
#define AXIIC_DS_3_IDM_INTERRUPT_STATUS			0x1811ea00
#endif /* !defined(CONFIG_MACH_GH2) */

#endif /* defined(CONFIG_MACH_HX4) || defined(CONFIG_MACH_KT2) || \
		defined(CONFIG_MACH_HR2) */

#if defined(CONFIG_MACH_GH) || defined(CONFIG_MACH_SB2) || \
		defined(CONFIG_MACH_GH2)
#define IDM_IO_PHYS_TO_VIRT(x) (void __iomem *) \
	(((x & 0xFFF00000) == (int)get_iproc_idm_base_phys(0))? \
		get_iproc_idm_base(0) + x - get_iproc_idm_base_phys(0) : \
		get_iproc_idm_base(1) + x - get_iproc_idm_base_phys(1))
#else
#define IDM_IO_PHYS_TO_VIRT(x) (void __iomem *) \
	(get_iproc_idm_base(0) + x - get_iproc_idm_base_phys(0))
#endif 


#define IHOST_S1_IDM_ERROR_LOG_CONTROL_VA IDM_IO_PHYS_TO_VIRT(IHOST_S1_IDM_ERROR_LOG_CONTROL)
#define IHOST_S1_IDM_ERROR_LOG_COMPLETE_VA IDM_IO_PHYS_TO_VIRT(IHOST_S1_IDM_ERROR_LOG_COMPLETE)
#define IHOST_S1_IDM_ERROR_LOG_STATUS_VA IDM_IO_PHYS_TO_VIRT(IHOST_S1_IDM_ERROR_LOG_STATUS)
#define IHOST_S1_IDM_ERROR_LOG_ADDR_LSB_VA IDM_IO_PHYS_TO_VIRT(IHOST_S1_IDM_ERROR_LOG_ADDR_LSB)
#define IHOST_S1_IDM_ERROR_LOG_ID_VA IDM_IO_PHYS_TO_VIRT(IHOST_S1_IDM_ERROR_LOG_ID)
#define IHOST_S1_IDM_ERROR_LOG_FLAGS_VA IDM_IO_PHYS_TO_VIRT(IHOST_S1_IDM_ERROR_LOG_FLAGS)

#define IHOST_S0_IDM_ERROR_LOG_CONTROL_VA IDM_IO_PHYS_TO_VIRT(IHOST_S0_IDM_ERROR_LOG_CONTROL)
#define IHOST_S0_IDM_ERROR_LOG_COMPLETE_VA IDM_IO_PHYS_TO_VIRT(IHOST_S0_IDM_ERROR_LOG_COMPLETE)
#define IHOST_S0_IDM_ERROR_LOG_STATUS_VA IDM_IO_PHYS_TO_VIRT(IHOST_S0_IDM_ERROR_LOG_STATUS)
#define IHOST_S0_IDM_ERROR_LOG_ADDR_LSB_VA IDM_IO_PHYS_TO_VIRT(IHOST_S0_IDM_ERROR_LOG_ADDR_LSB)
#define IHOST_S0_IDM_ERROR_LOG_ID_VA IDM_IO_PHYS_TO_VIRT(IHOST_S0_IDM_ERROR_LOG_ID)
#define IHOST_S0_IDM_ERROR_LOG_FLAGS_VA IDM_IO_PHYS_TO_VIRT(IHOST_S0_IDM_ERROR_LOG_FLAGS)

#define DDR_S1_IDM_ERROR_LOG_CONTROL_VA IDM_IO_PHYS_TO_VIRT(DDR_S1_IDM_ERROR_LOG_CONTROL)
#define DDR_S1_IDM_ERROR_LOG_COMPLETE_VA IDM_IO_PHYS_TO_VIRT(DDR_S1_IDM_ERROR_LOG_COMPLETE)
#define DDR_S1_IDM_ERROR_LOG_STATUS_VA IDM_IO_PHYS_TO_VIRT(DDR_S1_IDM_ERROR_LOG_STATUS)
#define DDR_S1_IDM_ERROR_LOG_ADDR_LSB_VA IDM_IO_PHYS_TO_VIRT(DDR_S1_IDM_ERROR_LOG_ADDR_LSB)
#define DDR_S1_IDM_ERROR_LOG_ID_VA IDM_IO_PHYS_TO_VIRT(DDR_S1_IDM_ERROR_LOG_ID)
#define DDR_S1_IDM_ERROR_LOG_FLAGS_VA IDM_IO_PHYS_TO_VIRT(DDR_S1_IDM_ERROR_LOG_FLAGS)

#define DDR_S2_IDM_ERROR_LOG_CONTROL_VA IDM_IO_PHYS_TO_VIRT(DDR_S2_IDM_ERROR_LOG_CONTROL)
#define DDR_S2_IDM_ERROR_LOG_COMPLETE_VA IDM_IO_PHYS_TO_VIRT(DDR_S2_IDM_ERROR_LOG_COMPLETE)
#define DDR_S2_IDM_ERROR_LOG_STATUS_VA IDM_IO_PHYS_TO_VIRT(DDR_S2_IDM_ERROR_LOG_STATUS)
#define DDR_S2_IDM_ERROR_LOG_ADDR_LSB_VA IDM_IO_PHYS_TO_VIRT(DDR_S2_IDM_ERROR_LOG_ADDR_LSB)
#define DDR_S2_IDM_ERROR_LOG_ID_VA IDM_IO_PHYS_TO_VIRT(DDR_S2_IDM_ERROR_LOG_ID)
#define DDR_S2_IDM_ERROR_LOG_FLAGS_VA IDM_IO_PHYS_TO_VIRT(DDR_S2_IDM_ERROR_LOG_FLAGS)

#define AXI_PCIE_S0_IDM_IDM_ERROR_LOG_CONTROL_VA IDM_IO_PHYS_TO_VIRT(AXI_PCIE_S0_IDM_IDM_ERROR_LOG_CONTROL)
#define AXI_PCIE_S0_IDM_IDM_ERROR_LOG_COMPLETE_VA IDM_IO_PHYS_TO_VIRT(AXI_PCIE_S0_IDM_IDM_ERROR_LOG_COMPLETE)
#define AXI_PCIE_S0_IDM_IDM_ERROR_LOG_STATUS_VA IDM_IO_PHYS_TO_VIRT(AXI_PCIE_S0_IDM_IDM_ERROR_LOG_STATUS)
#define AXI_PCIE_S0_IDM_IDM_ERROR_LOG_ADDR_LSB_VA IDM_IO_PHYS_TO_VIRT(AXI_PCIE_S0_IDM_IDM_ERROR_LOG_ADDR_LSB)
#define AXI_PCIE_S0_IDM_IDM_ERROR_LOG_ID_VA IDM_IO_PHYS_TO_VIRT(AXI_PCIE_S0_IDM_IDM_ERROR_LOG_ID)
#define AXI_PCIE_S0_IDM_IDM_ERROR_LOG_FLAGS_VA IDM_IO_PHYS_TO_VIRT(AXI_PCIE_S0_IDM_IDM_ERROR_LOG_FLAGS)

#define CMICD_S0_IDM_IDM_ERROR_LOG_CONTROL_VA IDM_IO_PHYS_TO_VIRT(CMICD_S0_IDM_IDM_ERROR_LOG_CONTROL)
#define CMICD_S0_IDM_IDM_ERROR_LOG_COMPLETE_VA IDM_IO_PHYS_TO_VIRT(CMICD_S0_IDM_IDM_ERROR_LOG_COMPLETE)
#define CMICD_S0_IDM_IDM_ERROR_LOG_STATUS_VA IDM_IO_PHYS_TO_VIRT(CMICD_S0_IDM_IDM_ERROR_LOG_STATUS)
#define CMICD_S0_IDM_IDM_ERROR_LOG_ADDR_LSB_VA IDM_IO_PHYS_TO_VIRT(CMICD_S0_IDM_IDM_ERROR_LOG_ADDR_LSB)
#define CMICD_S0_IDM_IDM_ERROR_LOG_ID_VA IDM_IO_PHYS_TO_VIRT(CMICD_S0_IDM_IDM_ERROR_LOG_ID)
#define CMICD_S0_IDM_IDM_ERROR_LOG_FLAGS_VA IDM_IO_PHYS_TO_VIRT(CMICD_S0_IDM_IDM_ERROR_LOG_FLAGS)

#define APBY_S0_IDM_IDM_ERROR_LOG_CONTROL_VA IDM_IO_PHYS_TO_VIRT(APBY_S0_IDM_IDM_ERROR_LOG_CONTROL)
#define APBY_S0_IDM_IDM_ERROR_LOG_COMPLETE_VA IDM_IO_PHYS_TO_VIRT(APBY_S0_IDM_IDM_ERROR_LOG_COMPLETE)
#define APBY_S0_IDM_IDM_ERROR_LOG_STATUS_VA IDM_IO_PHYS_TO_VIRT(APBY_S0_IDM_IDM_ERROR_LOG_STATUS)
#define APBY_S0_IDM_IDM_ERROR_LOG_ADDR_LSB_VA IDM_IO_PHYS_TO_VIRT(APBY_S0_IDM_IDM_ERROR_LOG_ADDR_LSB)
#define APBY_S0_IDM_IDM_ERROR_LOG_ID_VA IDM_IO_PHYS_TO_VIRT(APBY_S0_IDM_IDM_ERROR_LOG_ID)
#define APBY_S0_IDM_IDM_ERROR_LOG_FLAGS_VA IDM_IO_PHYS_TO_VIRT(APBY_S0_IDM_IDM_ERROR_LOG_FLAGS)

#define ROM_S0_IDM_ERROR_LOG_CONTROL_VA IDM_IO_PHYS_TO_VIRT(ROM_S0_IDM_ERROR_LOG_CONTROL)
#define ROM_S0_IDM_ERROR_LOG_COMPLETE_VA IDM_IO_PHYS_TO_VIRT(ROM_S0_IDM_ERROR_LOG_COMPLETE)
#define ROM_S0_IDM_ERROR_LOG_STATUS_VA IDM_IO_PHYS_TO_VIRT(ROM_S0_IDM_ERROR_LOG_STATUS)
#define ROM_S0_IDM_ERROR_LOG_ADDR_LSB_VA IDM_IO_PHYS_TO_VIRT(ROM_S0_IDM_ERROR_LOG_ADDR_LSB)
#define ROM_S0_IDM_ERROR_LOG_ID_VA IDM_IO_PHYS_TO_VIRT(ROM_S0_IDM_ERROR_LOG_ID)
#define ROM_S0_IDM_ERROR_LOG_FLAGS_VA IDM_IO_PHYS_TO_VIRT(ROM_S0_IDM_ERROR_LOG_FLAGS)

#define NAND_IDM_IDM_ERROR_LOG_CONTROL_VA IDM_IO_PHYS_TO_VIRT(NAND_IDM_IDM_ERROR_LOG_CONTROL)
#define NAND_IDM_IDM_ERROR_LOG_COMPLETE_VA IDM_IO_PHYS_TO_VIRT(NAND_IDM_IDM_ERROR_LOG_COMPLETE)
#define NAND_IDM_IDM_ERROR_LOG_STATUS_VA IDM_IO_PHYS_TO_VIRT(NAND_IDM_IDM_ERROR_LOG_STATUS)
#define NAND_IDM_IDM_ERROR_LOG_ADDR_LSB_VA IDM_IO_PHYS_TO_VIRT(NAND_IDM_IDM_ERROR_LOG_ADDR_LSB)
#define NAND_IDM_IDM_ERROR_LOG_ID_VA IDM_IO_PHYS_TO_VIRT(NAND_IDM_IDM_ERROR_LOG_ID)
#define NAND_IDM_IDM_ERROR_LOG_FLAGS_VA IDM_IO_PHYS_TO_VIRT(NAND_IDM_IDM_ERROR_LOG_FLAGS)

#define QSPI_IDM_IDM_ERROR_LOG_CONTROL_VA IDM_IO_PHYS_TO_VIRT(QSPI_IDM_IDM_ERROR_LOG_CONTROL)
#define QSPI_IDM_IDM_ERROR_LOG_COMPLETE_VA IDM_IO_PHYS_TO_VIRT(QSPI_IDM_IDM_ERROR_LOG_COMPLETE)
#define QSPI_IDM_IDM_ERROR_LOG_STATUS_VA IDM_IO_PHYS_TO_VIRT(QSPI_IDM_IDM_ERROR_LOG_STATUS)
#define QSPI_IDM_IDM_ERROR_LOG_ADDR_LSB_VA IDM_IO_PHYS_TO_VIRT(QSPI_IDM_IDM_ERROR_LOG_ADDR_LSB)
#define QSPI_IDM_IDM_ERROR_LOG_ID_VA IDM_IO_PHYS_TO_VIRT(QSPI_IDM_IDM_ERROR_LOG_ID)
#define QSPI_IDM_IDM_ERROR_LOG_FLAGS_VA IDM_IO_PHYS_TO_VIRT(QSPI_IDM_IDM_ERROR_LOG_FLAGS)

#define A9JTAG_S0_IDM_IDM_ERROR_LOG_CONTROL_VA IDM_IO_PHYS_TO_VIRT(A9JTAG_S0_IDM_IDM_ERROR_LOG_CONTROL)
#define A9JTAG_S0_IDM_IDM_ERROR_LOG_COMPLETE_VA IDM_IO_PHYS_TO_VIRT(A9JTAG_S0_IDM_IDM_ERROR_LOG_COMPLETE)
#define A9JTAG_S0_IDM_IDM_ERROR_LOG_STATUS_VA IDM_IO_PHYS_TO_VIRT(A9JTAG_S0_IDM_IDM_ERROR_LOG_STATUS)
#define A9JTAG_S0_IDM_IDM_ERROR_LOG_ADDR_LSB_VA IDM_IO_PHYS_TO_VIRT(A9JTAG_S0_IDM_IDM_ERROR_LOG_ADDR_LSB)
#define A9JTAG_S0_IDM_IDM_ERROR_LOG_ID_VA IDM_IO_PHYS_TO_VIRT(A9JTAG_S0_IDM_IDM_ERROR_LOG_ID)
#define A9JTAG_S0_IDM_IDM_ERROR_LOG_FLAGS_VA IDM_IO_PHYS_TO_VIRT(A9JTAG_S0_IDM_IDM_ERROR_LOG_FLAGS)

#define SRAM_S0_IDM_ERROR_LOG_CONTROL_VA IDM_IO_PHYS_TO_VIRT(SRAM_S0_IDM_ERROR_LOG_CONTROL)
#define SRAM_S0_IDM_ERROR_LOG_COMPLETE_VA IDM_IO_PHYS_TO_VIRT(SRAM_S0_IDM_ERROR_LOG_COMPLETE)
#define SRAM_S0_IDM_ERROR_LOG_STATUS_VA IDM_IO_PHYS_TO_VIRT(SRAM_S0_IDM_ERROR_LOG_STATUS)
#define SRAM_S0_IDM_ERROR_LOG_ADDR_LSB_VA IDM_IO_PHYS_TO_VIRT(SRAM_S0_IDM_ERROR_LOG_ADDR_LSB)
#define SRAM_S0_IDM_ERROR_LOG_ID_VA IDM_IO_PHYS_TO_VIRT(SRAM_S0_IDM_ERROR_LOG_ID)
#define SRAM_S0_IDM_ERROR_LOG_FLAGS_VA IDM_IO_PHYS_TO_VIRT(SRAM_S0_IDM_ERROR_LOG_FLAGS)

#define APBZ_S0_IDM_IDM_ERROR_LOG_CONTROL_VA IDM_IO_PHYS_TO_VIRT(APBZ_S0_IDM_IDM_ERROR_LOG_CONTROL)
#define APBZ_S0_IDM_IDM_ERROR_LOG_COMPLETE_VA IDM_IO_PHYS_TO_VIRT(APBZ_S0_IDM_IDM_ERROR_LOG_COMPLETE)
#define APBZ_S0_IDM_IDM_ERROR_LOG_STATUS_VA IDM_IO_PHYS_TO_VIRT(APBZ_S0_IDM_IDM_ERROR_LOG_STATUS)
#define APBZ_S0_IDM_IDM_ERROR_LOG_ADDR_LSB_VA IDM_IO_PHYS_TO_VIRT(APBZ_S0_IDM_IDM_ERROR_LOG_ADDR_LSB)
#define APBZ_S0_IDM_IDM_ERROR_LOG_ID_VA IDM_IO_PHYS_TO_VIRT(APBZ_S0_IDM_IDM_ERROR_LOG_ID)
#define APBZ_S0_IDM_IDM_ERROR_LOG_FLAGS_VA IDM_IO_PHYS_TO_VIRT(APBZ_S0_IDM_IDM_ERROR_LOG_FLAGS)

#define AXIIC_DS_3_IDM_ERROR_LOG_CONTROL_VA IDM_IO_PHYS_TO_VIRT(AXIIC_DS_3_IDM_ERROR_LOG_CONTROL)
#define AXIIC_DS_3_IDM_ERROR_LOG_COMPLETE_VA IDM_IO_PHYS_TO_VIRT(AXIIC_DS_3_IDM_ERROR_LOG_COMPLETE)
#define AXIIC_DS_3_IDM_ERROR_LOG_STATUS_VA IDM_IO_PHYS_TO_VIRT(AXIIC_DS_3_IDM_ERROR_LOG_STATUS)
#define AXIIC_DS_3_IDM_ERROR_LOG_ADDR_LSB_VA IDM_IO_PHYS_TO_VIRT(AXIIC_DS_3_IDM_ERROR_LOG_ADDR_LSB)
#define AXIIC_DS_3_IDM_ERROR_LOG_ID_VA IDM_IO_PHYS_TO_VIRT(AXIIC_DS_3_IDM_ERROR_LOG_ID)
#define AXIIC_DS_3_IDM_ERROR_LOG_FLAGS_VA IDM_IO_PHYS_TO_VIRT(AXIIC_DS_3_IDM_ERROR_LOG_FLAGS)

#define APBW_IDM_IDM_ERROR_LOG_CONTROL_VA IDM_IO_PHYS_TO_VIRT(APBW_IDM_IDM_ERROR_LOG_CONTROL)
#define APBW_IDM_IDM_ERROR_LOG_COMPLETE_VA IDM_IO_PHYS_TO_VIRT(APBW_IDM_IDM_ERROR_LOG_COMPLETE)
#define APBW_IDM_IDM_ERROR_LOG_STATUS_VA IDM_IO_PHYS_TO_VIRT(APBW_IDM_IDM_ERROR_LOG_STATUS)
#define APBW_IDM_IDM_ERROR_LOG_ADDR_LSB_VA IDM_IO_PHYS_TO_VIRT(APBW_IDM_IDM_ERROR_LOG_ADDR_LSB)
#define APBW_IDM_IDM_ERROR_LOG_ID_VA IDM_IO_PHYS_TO_VIRT(APBW_IDM_IDM_ERROR_LOG_ID)
#define APBW_IDM_IDM_ERROR_LOG_FLAGS_VA IDM_IO_PHYS_TO_VIRT(APBW_IDM_IDM_ERROR_LOG_FLAGS)

#define APBX_IDM_IDM_ERROR_LOG_CONTROL_VA IDM_IO_PHYS_TO_VIRT(APBX_IDM_IDM_ERROR_LOG_CONTROL)
#define APBX_IDM_IDM_ERROR_LOG_COMPLETE_VA IDM_IO_PHYS_TO_VIRT(APBX_IDM_IDM_ERROR_LOG_COMPLETE)
#define APBX_IDM_IDM_ERROR_LOG_STATUS_VA IDM_IO_PHYS_TO_VIRT(APBX_IDM_IDM_ERROR_LOG_STATUS)
#define APBX_IDM_IDM_ERROR_LOG_ADDR_LSB_VA IDM_IO_PHYS_TO_VIRT(APBX_IDM_IDM_ERROR_LOG_ADDR_LSB)
#define APBX_IDM_IDM_ERROR_LOG_ID_VA IDM_IO_PHYS_TO_VIRT(APBX_IDM_IDM_ERROR_LOG_ID)
#define APBX_IDM_IDM_ERROR_LOG_FLAGS_VA IDM_IO_PHYS_TO_VIRT(APBX_IDM_IDM_ERROR_LOG_FLAGS)

#define AXIIC_DS_0_IDM_ERROR_LOG_CONTROL_VA IDM_IO_PHYS_TO_VIRT(AXIIC_DS_0_IDM_ERROR_LOG_CONTROL)
#define AXIIC_DS_0_IDM_ERROR_LOG_COMPLETE_VA IDM_IO_PHYS_TO_VIRT(AXIIC_DS_0_IDM_ERROR_LOG_COMPLETE)
#define AXIIC_DS_0_IDM_ERROR_LOG_STATUS_VA IDM_IO_PHYS_TO_VIRT(AXIIC_DS_0_IDM_ERROR_LOG_STATUS)
#define AXIIC_DS_0_IDM_ERROR_LOG_ADDR_LSB_VA IDM_IO_PHYS_TO_VIRT(AXIIC_DS_0_IDM_ERROR_LOG_ADDR_LSB)
#define AXIIC_DS_0_IDM_ERROR_LOG_ID_VA IDM_IO_PHYS_TO_VIRT(AXIIC_DS_0_IDM_ERROR_LOG_ID)
#define AXIIC_DS_0_IDM_ERROR_LOG_FLAGS_VA IDM_IO_PHYS_TO_VIRT(AXIIC_DS_0_IDM_ERROR_LOG_FLAGS)

#define IDM_ERROR_LOG_ENABLE 0x33A
#define IDM_ERROR_LOG_CLEAR 0x3

#ifdef CONFIG_MACH_IPROC_P7

#if defined(CONFIG_MACH_HR3) || defined(CONFIG_MACH_GH2)
#define IHOST_S0_IDM_IRQ 52
#define DDR_S1_IDM_IRQ 53
#define DDR_S2_IDM_IRQ 54
#define AXI_PCIE_S0_IDM_IRQ 55
#define ROM_S0_IDM_IRQ 56
#define NAND_IDM_IRQ 57
#define QSPI_IDM_IRQ 58
#define PNOR_IDM_IRQ 59
#define SRAM_S0_IDM_IRQ 60
#define A9JTAG_S0_IDM_IRQ 61
#define APX_IDM_IRQ 64
#define CMICD_S0_IDM_IRQ 67
#define AXIIC_DS_0_IDM_IRQ 68
#define AXIIC_DS_1_IDM_IRQ 69
#define AXIIC_DS_2_IDM_IRQ 70
#else
#define IHOST_S0_IDM_IRQ 52
#define DDR_S1_IDM_IRQ 54
#define DDR_S2_IDM_IRQ 55
#define AXI_PCIE_S0_IDM_IRQ 56
#define AXI_PCIE_S1_IDM_IRQ 57
#define ROM_S0_IDM_IRQ 58
#define NAND_IDM_IRQ 59
#define QSPI_IDM_IRQ 60
#define SRAM_S0_IDM_IRQ 62
#define A9JTAG_S0_IDM_IRQ 64
#define APX_IDM_IRQ 68
#define CMICD_S0_IDM_IRQ 71
#define AXIIC_DS_0_IDM_IRQ 78
#define AXIIC_DS_1_IDM_IRQ 79
#define AXIIC_DS_2_IDM_IRQ 80
#define AXIIC_DS_3_IDM_IRQ 81
#endif /* defined(CONFIG_MACH_HR3) || defined(CONFIG_MACH_GH2) */

#else /* CONFIG_MACH_IPROC_P7 */

#define IHOST_S1_IDM_IRQ 62
#define IHOST_S0_IDM_IRQ 63
#define DDR_S1_IDM_IRQ 64
#define DDR_S2_IDM_IRQ 65
#define AXI_PCIE_S0_IDM_IRQ 66
#define AXI_PCIE_S1_IDM_IRQ 67
#define CMICD_S0_IDM_IRQ 68
#define ROM_S0_IDM_IRQ 69
#define NAND_IDM_IRQ 70
#define QSPI_IDM_IRQ 71
#define A9JTAG_S0_IDM_IRQ 73
#define SRAM_S0_IDM_IRQ 74
#define APW_IDM_IRQ 75
#define APX_IDM_IRQ 76
#define APBY_S0_IDM_IRQ 77
#define APBZ_S0_IDM_IRQ 78
#define AXIIC_DS_0_IDM_IRQ 79
#define AXIIC_DS_1_IDM_IRQ 80
#define AXIIC_DS_2_IDM_IRQ 81
#define AXIIC_DS_3_IDM_IRQ 82
#define AXIIC_DS_4_IDM_IRQ 83

#endif /* CONFIG_MACH_IPROC_P7 */

static irqreturn_t idm_timeout_handler(int val, void *ptr)
{
	u32 errval;
	
	printk(KERN_DEBUG "%s: %d, %d entry\n", __func__, __LINE__, val);
	errval = readl(IHOST_S1_IDM_ERROR_LOG_STATUS_VA);	
	if (errval > 0)
	{
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
		errval = readl(IHOST_S1_IDM_ERROR_LOG_ADDR_LSB_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(IHOST_S1_IDM_ERROR_LOG_ID_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(IHOST_S1_IDM_ERROR_LOG_FLAGS_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		writel(IDM_ERROR_LOG_CLEAR, IHOST_S1_IDM_ERROR_LOG_COMPLETE_VA);
		errval = readl(IHOST_S1_IDM_ERROR_LOG_STATUS_VA);
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
	}
	errval = readl(IHOST_S0_IDM_ERROR_LOG_STATUS_VA);
	if (errval > 0)
	{
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
		errval = readl(IHOST_S0_IDM_ERROR_LOG_ADDR_LSB_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(IHOST_S0_IDM_ERROR_LOG_ID_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(IHOST_S0_IDM_ERROR_LOG_FLAGS_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		writel(IDM_ERROR_LOG_CLEAR, IHOST_S0_IDM_ERROR_LOG_COMPLETE_VA);
		errval = readl(IHOST_S0_IDM_ERROR_LOG_STATUS_VA);
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
	}
	errval = readl(DDR_S1_IDM_ERROR_LOG_STATUS_VA);
	if (errval > 0)
	{
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
		errval = readl(DDR_S1_IDM_ERROR_LOG_ADDR_LSB_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(DDR_S1_IDM_ERROR_LOG_ID_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(DDR_S1_IDM_ERROR_LOG_FLAGS_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		writel(IDM_ERROR_LOG_CLEAR, DDR_S1_IDM_ERROR_LOG_COMPLETE_VA);
		errval = readl(DDR_S1_IDM_ERROR_LOG_STATUS_VA);
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
	}
	errval = readl(DDR_S2_IDM_ERROR_LOG_STATUS_VA);
	if (errval > 0)
	{
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
		errval = readl(DDR_S2_IDM_ERROR_LOG_ADDR_LSB_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(DDR_S2_IDM_ERROR_LOG_ID_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(DDR_S2_IDM_ERROR_LOG_FLAGS_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		writel(IDM_ERROR_LOG_CLEAR, DDR_S2_IDM_ERROR_LOG_COMPLETE_VA);
		errval = readl(DDR_S2_IDM_ERROR_LOG_STATUS_VA);
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
	}
	errval = readl(AXI_PCIE_S0_IDM_IDM_ERROR_LOG_STATUS_VA);
	if (errval > 0)
	{
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
		errval = readl(AXI_PCIE_S0_IDM_IDM_ERROR_LOG_ADDR_LSB_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(AXI_PCIE_S0_IDM_IDM_ERROR_LOG_ID_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(AXI_PCIE_S0_IDM_IDM_ERROR_LOG_FLAGS_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		writel(IDM_ERROR_LOG_CLEAR, AXI_PCIE_S0_IDM_IDM_ERROR_LOG_COMPLETE_VA);
		errval = readl(AXI_PCIE_S0_IDM_IDM_ERROR_LOG_STATUS_VA);
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
	}
	errval = readl(CMICD_S0_IDM_IDM_ERROR_LOG_STATUS_VA);
	if (errval > 0)
	{
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
		errval = readl(CMICD_S0_IDM_IDM_ERROR_LOG_ADDR_LSB_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(CMICD_S0_IDM_IDM_ERROR_LOG_ID_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(CMICD_S0_IDM_IDM_ERROR_LOG_FLAGS_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		writel(IDM_ERROR_LOG_CLEAR, CMICD_S0_IDM_IDM_ERROR_LOG_COMPLETE_VA);
		errval = readl(CMICD_S0_IDM_IDM_ERROR_LOG_STATUS_VA);
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
	}
#if !defined(CONFIG_MACH_IPROC_P7)
	errval = readl(APBY_S0_IDM_IDM_ERROR_LOG_STATUS_VA);
	if (errval > 0)
	{
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
		errval = readl(APBY_S0_IDM_IDM_ERROR_LOG_ADDR_LSB_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(APBY_S0_IDM_IDM_ERROR_LOG_ID_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(APBY_S0_IDM_IDM_ERROR_LOG_FLAGS_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		writel(IDM_ERROR_LOG_CLEAR, APBY_S0_IDM_IDM_ERROR_LOG_COMPLETE_VA);
		errval = readl(APBY_S0_IDM_IDM_ERROR_LOG_STATUS_VA);
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
	}
#endif
	errval = readl(ROM_S0_IDM_ERROR_LOG_STATUS_VA);
	if (errval > 0)
	{
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
		errval = readl(ROM_S0_IDM_ERROR_LOG_ADDR_LSB_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(ROM_S0_IDM_ERROR_LOG_ID_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(ROM_S0_IDM_ERROR_LOG_FLAGS_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		writel(IDM_ERROR_LOG_CLEAR, ROM_S0_IDM_ERROR_LOG_COMPLETE_VA);
		errval = readl(ROM_S0_IDM_ERROR_LOG_STATUS_VA);
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
	}
	errval = readl(NAND_IDM_IDM_ERROR_LOG_STATUS_VA);
	if (errval > 0)
	{
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
		errval = readl(NAND_IDM_IDM_ERROR_LOG_ADDR_LSB_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(NAND_IDM_IDM_ERROR_LOG_ID_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(NAND_IDM_IDM_ERROR_LOG_FLAGS_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		writel(IDM_ERROR_LOG_CLEAR, NAND_IDM_IDM_ERROR_LOG_COMPLETE_VA);
		errval = readl(NAND_IDM_IDM_ERROR_LOG_STATUS_VA);
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
	}
	errval = readl(QSPI_IDM_IDM_ERROR_LOG_STATUS_VA);
	if (errval > 0)
	{
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
		errval = readl(QSPI_IDM_IDM_ERROR_LOG_ADDR_LSB_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(QSPI_IDM_IDM_ERROR_LOG_ID_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(QSPI_IDM_IDM_ERROR_LOG_FLAGS_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		writel(IDM_ERROR_LOG_CLEAR, QSPI_IDM_IDM_ERROR_LOG_COMPLETE_VA);
		errval = readl(QSPI_IDM_IDM_ERROR_LOG_STATUS_VA);
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
	}
	errval = readl(A9JTAG_S0_IDM_IDM_ERROR_LOG_STATUS_VA);
	if (errval > 0)
	{
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
		errval = readl(A9JTAG_S0_IDM_IDM_ERROR_LOG_ADDR_LSB_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(A9JTAG_S0_IDM_IDM_ERROR_LOG_ID_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(A9JTAG_S0_IDM_IDM_ERROR_LOG_FLAGS_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		writel(IDM_ERROR_LOG_CLEAR, A9JTAG_S0_IDM_IDM_ERROR_LOG_COMPLETE_VA);
		errval = readl(A9JTAG_S0_IDM_IDM_ERROR_LOG_STATUS_VA);
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
	}
#if !defined(CONFIG_MACH_IPROC_P7)
	errval = readl(SRAM_S0_IDM_ERROR_LOG_STATUS_VA);
	if (errval > 0)
	{
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
		errval = readl(SRAM_S0_IDM_ERROR_LOG_ADDR_LSB_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(SRAM_S0_IDM_ERROR_LOG_ID_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(SRAM_S0_IDM_ERROR_LOG_FLAGS_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		writel(IDM_ERROR_LOG_CLEAR, SRAM_S0_IDM_ERROR_LOG_COMPLETE_VA);
		errval = readl(SRAM_S0_IDM_ERROR_LOG_STATUS_VA);
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
	}
	errval = readl(APBZ_S0_IDM_IDM_ERROR_LOG_STATUS_VA);
	if (errval > 0)
	{
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
		errval = readl(APBZ_S0_IDM_IDM_ERROR_LOG_ADDR_LSB_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(APBZ_S0_IDM_IDM_ERROR_LOG_ID_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(APBZ_S0_IDM_IDM_ERROR_LOG_FLAGS_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		writel(IDM_ERROR_LOG_CLEAR, APBZ_S0_IDM_IDM_ERROR_LOG_COMPLETE_VA);
		errval = readl(APBZ_S0_IDM_IDM_ERROR_LOG_STATUS_VA);
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
	}
#endif

#if !defined(CONFIG_MACH_HR3) && !defined(CONFIG_MACH_GH2)
	errval = readl(AXIIC_DS_3_IDM_ERROR_LOG_STATUS_VA);
	if (errval > 0)
	{
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
		errval = readl(AXIIC_DS_3_IDM_ERROR_LOG_ADDR_LSB_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(AXIIC_DS_3_IDM_ERROR_LOG_ID_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(AXIIC_DS_3_IDM_ERROR_LOG_FLAGS_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		writel(IDM_ERROR_LOG_CLEAR, AXIIC_DS_3_IDM_ERROR_LOG_COMPLETE_VA);
		errval = readl(AXIIC_DS_3_IDM_ERROR_LOG_STATUS_VA);
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
	}
#endif /* !defined(CONFIG_MACH_HR3) && !defined(CONFIG_MACH_GH2)*/

#if !defined(CONFIG_MACH_IPROC_P7)
	errval = readl(APBW_IDM_IDM_ERROR_LOG_STATUS_VA);
	if (errval > 0)
	{
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
		errval = readl(APBW_IDM_IDM_ERROR_LOG_ADDR_LSB_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(APBW_IDM_IDM_ERROR_LOG_ID_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(APBW_IDM_IDM_ERROR_LOG_FLAGS_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		writel(IDM_ERROR_LOG_CLEAR, APBW_IDM_IDM_ERROR_LOG_COMPLETE_VA);
		errval = readl(APBW_IDM_IDM_ERROR_LOG_STATUS_VA);
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
	}
#endif
	errval = readl(APBX_IDM_IDM_ERROR_LOG_STATUS_VA);
	if (errval > 0)
	{
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
		errval = readl(APBX_IDM_IDM_ERROR_LOG_ADDR_LSB_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(APBX_IDM_IDM_ERROR_LOG_ID_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(APBX_IDM_IDM_ERROR_LOG_FLAGS_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		writel(IDM_ERROR_LOG_CLEAR, APBX_IDM_IDM_ERROR_LOG_COMPLETE_VA);
		errval = readl(APBX_IDM_IDM_ERROR_LOG_STATUS_VA);
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
	}
	errval = readl(AXIIC_DS_0_IDM_ERROR_LOG_STATUS_VA);
	if (errval > 0)
	{
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
		errval = readl(AXIIC_DS_0_IDM_ERROR_LOG_ADDR_LSB_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(AXIIC_DS_0_IDM_ERROR_LOG_ID_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		errval = readl(AXIIC_DS_0_IDM_ERROR_LOG_FLAGS_VA);
		printk(KERN_DEBUG "%s: %d, %08x\n", __func__, __LINE__, errval);
		writel(IDM_ERROR_LOG_CLEAR, AXIIC_DS_0_IDM_ERROR_LOG_COMPLETE_VA);
		errval = readl(AXIIC_DS_0_IDM_ERROR_LOG_STATUS_VA);
		printk(KERN_DEBUG "%s: %d, %d\n", __func__, __LINE__, errval);
	}

	return IRQ_HANDLED;
}

void init_request_idm_timeout(void)
{
	/* clear all pending idm interrupts */
	idm_timeout_handler(0, NULL);
   
	/* enable idm error log for all slaves */

	writel(IDM_ERROR_LOG_ENABLE, IHOST_S1_IDM_ERROR_LOG_CONTROL_VA);
	writel(IDM_ERROR_LOG_ENABLE, IHOST_S0_IDM_ERROR_LOG_COMPLETE_VA);
	writel(IDM_ERROR_LOG_ENABLE, DDR_S1_IDM_ERROR_LOG_COMPLETE_VA);
	writel(IDM_ERROR_LOG_ENABLE, DDR_S2_IDM_ERROR_LOG_COMPLETE_VA);
	writel(IDM_ERROR_LOG_ENABLE, AXI_PCIE_S0_IDM_IDM_ERROR_LOG_CONTROL_VA);
	writel(IDM_ERROR_LOG_ENABLE, CMICD_S0_IDM_IDM_ERROR_LOG_CONTROL_VA);

#if !defined(CONFIG_MACH_HR3) && !defined(CONFIG_MACH_GH2)
	writel(IDM_ERROR_LOG_ENABLE, SRAM_S0_IDM_ERROR_LOG_CONTROL_VA);
#endif /* !defined(CONFIG_MACH_HR3) && !defined(CONFIG_MACH_GH2)*/

#ifndef CONFIG_MACH_IPROC_P7
	writel(IDM_ERROR_LOG_ENABLE, APBY_S0_IDM_IDM_ERROR_LOG_CONTROL_VA);
	writel(IDM_ERROR_LOG_ENABLE, APBZ_S0_IDM_IDM_ERROR_LOG_CONTROL_VA);
	writel(IDM_ERROR_LOG_ENABLE, APBW_IDM_IDM_ERROR_LOG_CONTROL_VA);
#endif

	writel(IDM_ERROR_LOG_ENABLE, ROM_S0_IDM_ERROR_LOG_CONTROL_VA);
	writel(IDM_ERROR_LOG_ENABLE, NAND_IDM_IDM_ERROR_LOG_CONTROL_VA);
	writel(IDM_ERROR_LOG_ENABLE, QSPI_IDM_IDM_ERROR_LOG_CONTROL_VA);
	writel(IDM_ERROR_LOG_ENABLE, A9JTAG_S0_IDM_IDM_ERROR_LOG_CONTROL_VA);
#if !defined(CONFIG_MACH_HR3) && !defined(CONFIG_MACH_GH2)
	writel(IDM_ERROR_LOG_ENABLE, AXIIC_DS_3_IDM_ERROR_LOG_COMPLETE_VA);
#endif /* !defined(CONFIG_MACH_HR3) && !defined(CONFIG_MACH_GH2) */
	writel(IDM_ERROR_LOG_ENABLE, APBX_IDM_IDM_ERROR_LOG_CONTROL_VA);
	writel(IDM_ERROR_LOG_ENABLE, AXIIC_DS_0_IDM_ERROR_LOG_CONTROL_VA);
}

int request_idm_timeout_interrupts(struct device_node *np)
{
	int i, ret, irq;
	unsigned int irqs_total;
	
	init_request_idm_timeout();
	
	irqs_total = of_irq_count(np);
  	if (!irqs_total)
  		return -EINVAL;
  		
  	for (i=0; i<irqs_total; i++) {
  		irq = irq_of_parse_and_map(np, i);
		ret = request_irq(irq, (irq_handler_t)idm_timeout_handler, 
			IRQF_PERCPU, "IDM", NULL);
		if (ret != 0)
			printk(KERN_WARNING "%s: %d request_irq return = %d\n", __func__, __LINE__, ret);	
	}
	
	return 0;
}